// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWlme--pWMrS1pIFLApTmqU0x9BhAUMY8',
    appId: '1:708026884574:web:77bb9c1cdf11c8c5eafd4f',
    messagingSenderId: '708026884574',
    projectId: 'ecommercelatest',
    authDomain: 'ecommercelatest.firebaseapp.com',
    storageBucket: 'ecommercelatest.firebasestorage.app',
    measurementId: 'G-NM091TLV2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2-PpBjN6ueqbsWlSXj_QltNsSdu03uUQ',
    appId: '1:708026884574:android:a4f99464893b2b8feafd4f',
    messagingSenderId: '708026884574',
    projectId: 'ecommercelatest',
    storageBucket: 'ecommercelatest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8FdouMUYWp9q2bqlk0uMVt-ZGlCyxOhI',
    appId: '1:708026884574:ios:8ac197f3b2aed9b9eafd4f',
    messagingSenderId: '708026884574',
    projectId: 'ecommercelatest',
    storageBucket: 'ecommercelatest.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8FdouMUYWp9q2bqlk0uMVt-ZGlCyxOhI',
    appId: '1:708026884574:ios:8ac197f3b2aed9b9eafd4f',
    messagingSenderId: '708026884574',
    projectId: 'ecommercelatest',
    storageBucket: 'ecommercelatest.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWlme--pWMrS1pIFLApTmqU0x9BhAUMY8',
    appId: '1:708026884574:web:d3ce4f67f82485d0eafd4f',
    messagingSenderId: '708026884574',
    projectId: 'ecommercelatest',
    authDomain: 'ecommercelatest.firebaseapp.com',
    storageBucket: 'ecommercelatest.firebasestorage.app',
    measurementId: 'G-Z4YFYQQWVZ',
  );

}